/**
 * Cross-agent classification helpers for the part model.
 *
 * - `splitInjected` separates a raw "user" text into the human prompt and the
 *   context blocks harnesses/IDEs wrap around it (`<system-reminder>`,
 *   `<recommended_plugins>`, `<timestamp>`, `<system_notification>`, ...).
 * - `toolCategory` maps tool names from every agent onto one vocabulary.
 * - `extractFiles` / `extractCommand` pull retrieval keys out of arguments.
 */
import type { ContextForm, ToolCategory } from "./types";

type Rec = Record<string, unknown>;

// ---------- injected context ----------

/** Tag → form. Anything matched here is context, not a human utterance. */
const TAG_FORMS: Record<string, ContextForm> = {
  // instructions
  "system-reminder": "instructions",
  system_reminder: "instructions",
  user_instructions: "instructions",
  "permissions instructions": "instructions",
  recommended_plugins: "instructions",
  rules: "instructions",
  agent_rules: "instructions",
  always_applied_workspace_rules: "instructions",
  user_rules: "instructions",
  agent_skills: "instructions",
  available_skills: "instructions",
  "command-name": "instructions",
  "command-message": "instructions",
  "command-args": "instructions",
  // snapshot
  environment_context: "snapshot",
  environment_details: "snapshot",
  current_datetime: "snapshot",
  timestamp: "snapshot",
  git_status: "snapshot",
  user_info: "snapshot",
  workspace_info: "snapshot",
  open_files: "snapshot",
  "local-command-stdout": "snapshot",
  ide_selection: "snapshot",
  ide_opened_file: "snapshot",
  cursor_position: "snapshot",
  agent_transcripts: "snapshot",
  terminals: "snapshot",
  dynamic_tool_catalog: "snapshot",
  current_focus: "snapshot",
  realtime_delegation: "instructions",
  external_links: "attachment",
  // notices
  system_notification: "notice",
  "task-notification": "notice",
  task_notification: "notice",
  turn_aborted: "notice",
  system: "notice",
  // attachments
  attached_files: "attachment",
  uploaded_files: "attachment",
  attachments: "attachment",
  additional_data: "attachment",
  file_contents: "attachment",
  selected_code: "attachment",
  // recall
  memory: "recall",
  memories: "recall",
  past_chats: "recall",
  recalled_sessions: "recall",
  session_reference: "recall",
};

/** Tags that wrap the human's actual text; the content is kept as prompt. */
const PROMPT_WRAPPERS = ["user_query", "user_message", "user_prompt", "query", "request", "human"];

const PLAIN_INJECTED_PREFIXES: [RegExp, ContextForm][] = [
  [/^# AGENTS\.md/i, "instructions"],
  [/^# CLAUDE\.md/i, "instructions"],
  [/^<environment_context>/i, "snapshot"],
  [/^<permissions instructions>/i, "instructions"],
  [/^<user_instructions>/i, "instructions"],
  [/^Caveat: The messages below were generated by the user while running local commands/i, "notice"],
  [/^This session is being continued from a previous conversation/i, "recall"],
  [/^The following is the Codex agent history/i, "recall"],
  [/^Briefly inform the user about the task result/i, "notice"],
];

export interface SplitInjected {
  /** Human text with wrappers removed. Empty when the message was pure context. */
  prompt: string;
  context: { form: ContextForm; tag: string; text: string }[];
}

/** `<tag attrs>body</tag>`; group 1 = tag name, group 2 = body. */
const TAG_RE = /<([a-zA-Z_][\w-]*)(?: [^<>]*)?>([\s\S]*?)<\/\1>/g;

/**
 * Split raw user-role text into prompt + context blocks. Handles nested
 * wrappers like `<user_query>...</user_query>` by unwrapping them and keeps
 * unknown tags as prompt text (they may be part of what the user typed).
 */
export function splitInjected(raw: string): SplitInjected {
  const context: SplitInjected["context"] = [];
  let rest = raw;
  // Iteratively strip known tags (handles several at top level; nesting of known tags inside known tags collapses into the outer block).
  let guard = 0;
  while (guard++ < 200) {
    TAG_RE.lastIndex = 0;
    let replaced = false;
    rest = rest.replace(TAG_RE, (whole, tagName: string, body: string) => {
      const tag = tagName.toLowerCase();
      const form = TAG_FORMS[tag];
      if (form) {
        context.push({ form, tag, text: body.trim() });
        replaced = true;
        return "\n";
      }
      if (PROMPT_WRAPPERS.includes(tag)) {
        replaced = true;
        return "\n" + body + "\n";
      }
      return whole;
    });
    if (!replaced) break;
  }
  // Self-closing / attribute-only attachment tags: <image path="…"/>, <file path="…">
  rest = rest.replace(/<(image|img|file|attachment|uploaded_file)\b([^<>]*)\/?>(?:\s*<\/\1>)?/gi, (_w, tag: string, attrs: string) => {
    context.push({ form: "attachment", tag: tag.toLowerCase(), text: attrs.trim() || tag });
    return "\n";
  });
  let prompt = rest.replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim();
  // A leading bare tag whose closing tag never arrived (truncated titles, streamed prompts) is not human text.
  prompt = prompt.replace(/^(<[a-zA-Z_][\w-]*>\s*)+/, "").trim();
  for (const [re, form] of PLAIN_INJECTED_PREFIXES) {
    if (re.test(prompt)) {
      context.push({ form, tag: "prefix", text: prompt });
      prompt = "";
      break;
    }
  }
  return { prompt, context };
}

/** True when the text is entirely harness-injected. */
export function isInjectedOnly(raw: string): boolean {
  return !splitInjected(raw).prompt;
}

// ---------- tool categories ----------

const CATEGORY_RULES: [RegExp, ToolCategory][] = [
  [/^(bash|shell|exec(_command)?|run_terminal(_cmd|_command)?(_v\d+)?|terminal|execute_command|run_command|run_shell_command|local_shell|command_execution|write_stdin|powershell|zsh|sh|runcommand|run_in_terminal|executeBash|execute_bash|run|run_process|process|code_execution|codeexecution|python|execute_code)$/i, "shell"],
  [/^(read|read_file(_v\d+)?|cat|view|view_file|open_file|list_dir|list_directory|ls|read_many_files|readFile|read_lints|get_file|file_read|list_files|directory_tree|view_image|read_multiple_files|readfile|glob_file_search)$/i, "read"],
  [/^(write|edit|edit_file(_v\d+)?|write_file|create_file|delete_file|apply_patch|apply_diff|str_replace(_based)?_edit(or|_tool)?|str_replace|multi_edit|multiedit|replace|replace_in_file|insert|insert_edit_into_file|create|patch|write_to_file|search_replace|search_and_replace|edit_tool|notebook_edit|editnotebook|edit_notebook|delete|remove_file|move_file|rename_file|mkdir|notebookedit|reapply|create_directory|writefile|editfile|smart_edit)$/i, "edit"],
  [/^(grep|glob|rg|ripgrep(_raw)?_search|codebase_search|search|search_files|semantic_search|find|find_files|search_codebase|file_search|grep_search|list_code_usages|search_symbols|search_replace_preview|regex_search|fuzzy_search|find_by_name|grep_tool|search_code|text_search)$/i, "search"],
  [/^(web_search|websearch|web_fetch|webfetch|fetch|fetch_url|browse|search_web|google_web_search|http_request|url_fetch|open_url|fetch_webpage|web_read|read_url|download|curl)$/i, "web"],
  [/^(task(_v\d+)?|agent|spawn_agent|wait_agent|close_agent|send_input|subagent|delegate|run_subagent|create_agent|dispatch_agent|resume_agent|launch_agent|send_message_to_agent|job_spawn|job_wait|job_kill|jobs?_.*|task_output|taskoutput)$/i, "subagent"],
  [/^(todo_?write|todowrite|todo_?read|update_plan|plan|write_plan|update_todo|manage_todo_list|exit_plan_mode|enter_plan_mode|create_plan|set_plan|todo|goal_.*|switch_?mode|switchmode)$/i, "plan"],
  [/^(ask_question|ask_user|askquestion|ask_followup_question|ask|request_user_input|question|attempt_completion|ask_user_question|askuserquestion|interaction|user_input)$/i, "ask"],
  [/^(browser_.*|playwright.*|screenshot|navigate|click|type_text|browser|computer|computer_use|open_browser|take_screenshot|cu_.*)$/i, "browser"],
];

const MCP_RE = /^(mcp__|mcp_|mcp-|user-|plugin-|cursor-|@)/i;

export function toolCategory(name: string, args?: unknown): ToolCategory {
  const n = name.trim();
  for (const [re, cat] of CATEGORY_RULES) if (re.test(n)) return cat;
  // MCP tools are usually prefixed; keep them distinguishable.
  if (MCP_RE.test(n)) return "mcp";
  // Heuristics on args when the name is opaque.
  if (isRec(args)) {
    if (typeof args.command === "string" || typeof args.cmd === "string") return "shell";
    if (typeof args.url === "string") return "web";
    if (typeof args.pattern === "string" || typeof args.query === "string") return "search";
    if (typeof args.old_string === "string" || typeof args.new_string === "string" || typeof args.content === "string") return "edit";
    if (typeof args.path === "string" || typeof args.file_path === "string") return "read";
  }
  return "other";
}

// ---------- argument extraction ----------

function isRec(v: unknown): v is Rec {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Parse arguments that arrive as a JSON string; return the original otherwise. */
export function parseArgs(input: unknown): unknown {
  if (typeof input !== "string") return input;
  const t = input.trim();
  if (!t.startsWith("{") && !t.startsWith("[")) return input;
  try {
    return JSON.parse(t);
  } catch {
    return input;
  }
}

const FILE_KEYS = ["path", "file_path", "filePath", "file", "target_file", "targetFile", "notebook_path", "relative_workspace_path", "target_notebook", "absolute_path", "filename", "file_name", "dir", "directory", "target_directory", "old_path", "new_path", "source", "destination"];
const FILE_LIST_KEYS = ["paths", "files", "file_paths", "filePaths"];
const COMMAND_KEYS = ["command", "cmd", "commandLine", "command_line", "script", "code"];

export function extractCommand(args: unknown): string | undefined {
  const a = parseArgs(args);
  if (typeof a === "string") return a.trim() || undefined;
  if (!isRec(a)) return undefined;
  for (const k of COMMAND_KEYS) {
    const v = a[k];
    if (typeof v === "string" && v.trim()) return v.trim();
    if (Array.isArray(v) && v.every((x) => typeof x === "string")) return (v as string[]).join(" ");
  }
  // codex local_shell_call: { action: { command: [...] } }
  if (isRec(a.action)) return extractCommand(a.action);
  return undefined;
}

const PATCH_FILE_RE = /^\*\*\* (?:Add|Update|Delete|Move to) File: (.+)$|^(?:---|\+\+\+) [ab]\/(.+)$|^diff --git a\/(\S+)/gm;

export function extractFiles(args: unknown, resultText?: string): string[] {
  const a = parseArgs(args);
  const out = new Set<string>();
  const add = (v: unknown) => {
    if (typeof v === "string" && v.trim() && v.length < 512 && !/\s{2,}/.test(v)) out.add(v.trim());
  };
  if (isRec(a)) {
    for (const k of FILE_KEYS) add(a[k]);
    for (const k of FILE_LIST_KEYS) if (Array.isArray(a[k])) for (const v of a[k] as unknown[]) add(v);
    // apply_patch style input
    const patch = typeof a.input === "string" ? a.input : typeof a.patch === "string" ? a.patch : undefined;
    if (patch) for (const m of patch.matchAll(PATCH_FILE_RE)) add(m[1] ?? m[2] ?? m[3]);
  } else if (typeof a === "string") {
    for (const m of a.matchAll(PATCH_FILE_RE)) add(m[1] ?? m[2] ?? m[3]);
  }
  if (resultText) for (const m of resultText.slice(0, 20_000).matchAll(/^\*\*\* (?:Add|Update|Delete) File: (.+)$/gm)) add(m[1]);
  return Array.from(out);
}

/** Compact one-line rendering of arguments for tables and snippets. */
export function renderArgs(name: string, args: unknown, max = 200): string {
  const cmd = extractCommand(args);
  if (cmd) return oneLine(cmd, max);
  const a = parseArgs(args);
  if (a === undefined || a === null) return "";
  if (typeof a === "string") return oneLine(a, max);
  if (isRec(a)) {
    const files = extractFiles(a);
    const parts: string[] = [];
    if (files.length) parts.push(files.join(", "));
    for (const [k, v] of Object.entries(a)) {
      if (FILE_KEYS.includes(k) || FILE_LIST_KEYS.includes(k)) continue;
      if (typeof v === "string") parts.push(`${k}: ${oneLine(v, 120)}`);
      else if (typeof v === "number" || typeof v === "boolean") parts.push(`${k}: ${v}`);
    }
    return oneLine(parts.join(" · ") || JSON.stringify(a), max);
  }
  return oneLine(JSON.stringify(a), max);
}

/** Full text rendering of arguments for the part body (searchable). */
export function argsToText(args: unknown): string {
  const a = parseArgs(args);
  if (a === undefined || a === null) return "";
  if (typeof a === "string") return a;
  if (isRec(a)) {
    // Keep strings verbatim (commands, patches, new file contents) so they are searchable; JSON-encode the rest.
    return Object.entries(a)
      .map(([k, v]) => (typeof v === "string" ? `${k}: ${v}` : `${k}: ${JSON.stringify(v)}`))
      .join("\n");
  }
  return JSON.stringify(a, null, 1);
}

export function oneLine(s: string, max: number): string {
  const one = s.replace(/\s+/g, " ").trim();
  return one.length > max ? one.slice(0, max - 1) + "…" : one;
}

/** Best-effort exit code / error detection on tool output. */
export function detectExit(text: string): { exitCode?: number; isError?: boolean } {
  const m = text.match(/(?:^|\n)\s*(?:exit code|Exit code|exit_code|Process exited with code|Command exited with code)[:=]?\s*(-?\d+)/);
  if (m) {
    const code = Number(m[1]);
    return { exitCode: code, isError: code !== 0 };
  }
  if (/^\s*(Error|error|ERROR|Traceback \(most recent call last\)|fatal:|command not found|No such file or directory|Permission denied)/m.test(text.slice(0, 400))) return { isError: true };
  return {};
}
